LogInterceptor - waitFor func
Naturaily/node-api-template pull request #4
Opened 2020-09-07 08:40 UTC by avemike

async waitFor function which repetitively calls predicate function until it returns true, or max iterations number / timeout will be reached

2020-09-07 23:32 UTC, kacepe commented on tests/integration/smoke.ts
> +          console.log(logInterceptor.getLogs());
Please remove console.log

2020-09-07 23:32 UTC, kacepe commented on tests/utils/LogInterceptor/index.ts
> +  async waitFor(predicate: (logs: string[]) => Promise<boolean>, timeout: number, maxIterations: number) {
Can we have any tests for it?

2020-09-07 23:37 UTC, kacepe commented on tests/utils/LogInterceptor/index.ts
> +  async waitFor(predicate: (logs: string[]) => Promise<boolean>, timeout: number, maxIterations: number) {
In smoke for example

2020-09-11 11:02 UTC, Dziejo93 requested changes

2020-09-11 11:02 UTC, Dziejo93 commented on tests/utils/LogInterceptor/index.ts
> +    while (Date.now() < finishTime && maxIterations--) {
imo `--` in if is misleading. I suggest to do it at the end of a while.

2020-09-11 11:02 UTC, Dziejo93 commented on tests/utils/LogInterceptor/index.ts
> +      throw new Error("Count of logs doesn't match expected count of logs");
"Count of logs => "Log count ? But I may be wrong :p

2020-09-11 11:03 UTC, Dziejo93 commented on tests/utils/LogInterceptor/index.ts
> +  async waitFor(predicate: (logs: string[]) => Promise<boolean>, timeout: number, maxIterations: number) {
maybe also unit test the class?

2020-09-15 12:15 UTC, Dziejo93 approved these changes

2020-09-16 14:21 UTC, kacepe approved these changes

2020-09-16 14:21 UTC, merged